//parameters
#define XS_PRM_DEFAULT "def"
#define XS_PRM_VERSION "version"
#define XS_PRM_SCALE "scale"
#define XS_PRM_ROOM_WALL "room_wall"
#define XS_PRM_BACKGROUND "background"
#define XS_PRM_PIC_EXTENSTIONS "picture_extensions"
#define XS_PRM_ZOOMSTEP "zoomstep"
#define XS_PRM_SELECTROOM "selectroom"
//objects
#define XS_PRM_ROOM "room"
#define XS_PRM_INFO "info"
#define XS_PRM_ROOMLIST "roomlist"
#define XS_PRM_ROOMNEXT "roomnext"
#define XS_PRM_ENDNEXT "endnext"
#define XS_PRM_SKIP "skip"
#define XS_PRM_LOGO "logo"
#define XS_PRM_PWALL "pwall"
#define XS_PRM_CWALL "cwall"
#define XS_PRM_LWALL "lwall"
#define XS_PRM_PLWALL "plwall"
#define XS_PRM_WALLLIST "walllist"
#define XS_PRM_WALL "wall"
#define XS_PRM_DOOR "door"
#define XS_PRM_DOORNEXT "doornext"
#define XS_PRM_FIXTEXT "fixtext"
#define XS_PRM_STAIR "stair"
#define XS_PRM_FULL "full"

#define XS_PRM_STRIP "strip"
//background
#define XS_PRM_PICTURE "pic"
#define XS_PRM_COLOR "color"
//#define XS_PRM_RED "r"
//#define XS_PRM_GREEN "g"
//#define XS_PRM_BLUE "b"
//backs
#define XS_PRM_MOSAIC "m"
#define XS_PRM_STRETCH "s"
#define XS_PRM_AREA "area"
#define XS_PRM_LAREA "larea"
//room and inner objects
#define XS_PRM_RECTANGLE "rect"
#define XS_PRM_POLYGONE "poly"
#define XS_PRM_VERTICAL "v"
#define XS_PRM_HORIZONTAL "h"
#define XS_PRM_ANGLE "a"
//#define XS_PRM_NONAME "noname"
//files
#define XS_FILE_DEFAULTS "/defaults.txt"
#define XS_FILE_DOORS "/doors.txt"
#define XS_FILE_WALLS "/walls.txt"
#define XS_FILE_BACKGROUNDS "/backgrounds/backgrounds.txt"
#define XS_FILE_LOGOS "/logos/logos.txt"
#define XS_FILE_BUILDS "/builds/builds.txt"
//#define XS_FILE_FLOORS "/builds/%d/floors.txt"
//#define XS_FILE_BACKS "/builds/%d/%d/backs.txt"
//#define XS_FILE_PLAN "/builds/%d/%d/plan.txt"
//#define XS_FILE_ROOMS "/builds/%d/%d/rooms.txt"
//#define XS_PATH_FLOOR "/builds/%d/"
//#define XS_PATH_BUILD "/builds/%d/%d/

#define XS_FILE_FLOORS "/floors.txt"
#define XS_FILE_BACKS "/backs.txt"
#define XS_FILE_PLAN "/plan.txt"
#define XS_FILE_ROOMS "/rooms.txt"

#define XS_FOLDER_BUILDS "/builds/"